name: pycon-d4a
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scipy
  - bokeh
  - seaborn
  - jupyterlab=3.0.12
  - pandas
  - pip
  - python=3.9
  - holoviews
  - param
  - hvplot
  - geoviews-core
  - datashader
  - nodejs
  - selenium
  - geckodriver
  - geopandas
  - panel
  - shapely
  - toolz
  - param
  - iris
  - colorcet
  - altair
  - geos
  - gdal
  - contextily
  - fiona
  - flask
  - geographiclib
  - geopy
  - itsdangerous
  - mapclassify
  - mercantile
  - networkx
  - pyarrow
  - pyproj
  - rasterio
  - rtree
  - tqdm