name: pycon-d4a
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter-panel-proxy
  - pip
  - numpy
  - matplotlib
  - scipy
  - bokeh
  - seaborn
  - jupyterlab
  - pandas
  - holoviews
  - param
  - hvplot
  - geoviews-core
  - datashader
  - nodejs
  - selenium
  - geopandas
  - panel
  - shapely
  - toolz
  - param
  - iris
  - colorcet
  - geos
  - gdal
  - firefox
  - geckodriver
  - pip:
    - fiona
    - flask
    - geopandas
    - geopy
    - networkx
    - pyarrow
    - pyproj
    - rasterio
    - rtree
    - tqdm
    - contextily
    - jupyter_bokeh
    - transformers
    - "gradio<4.0"
    - mlserver
    - torch
    - librosa
    - pedalboard
    - rich
    - faker